kind: List
api: v1
items:

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: kuill
    namespace: kube-system

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: kuill-serviceaccount
    namespace: kube-system
  rules:
  # ability to list namespaces is required in order
  # to drive self-subject-access-reviews for users
  # who are not authorized to all namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  # the following permissions are used to provide
  # metrics details (requested from the master 
  # via nodes/proxy -> status)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: [list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["proxy"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["*"]

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  metadata:
    name: kuill-serviceaccount
    namespace: kube-system
  subjects:
    - kind: ServiceAccount
      name: kuill
  roleRef:
    kind: Role
    name: kuill-serviceaccount
    apiGroup: "rbac.authorization.k8s.io"

- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    labels:
      name: kuill
    name: kuill
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: kuill
    template:
      metadata:
        labels:
          name: kuill
          service: kuill
      spec:
        volumes:
        - name: auth-proxy-certs
          secret:
            secretName: auth-proxy-certs
        containers:
        - image: mattdeboer/kuill
          name: kuill
          volumeMounts: 
          - name: auth-proxy-certs
            mountPath: /certs
            readOnly: true
          env:
          - name: kuill_PORT
            value: "8443"
          - name: kuill_ANONYMOUS_GROUPS
            value: system:masters
          - name: kuill_SERVER_CERT
            value: /certs/auth-proxy.pem
          - name: kuill_SERVER_KEY
            value: /certs/auth-proxy-key.pem
          - name: kuill_KUBERNETES_CLIENT_CERT
            value: /certs/auth-proxy.pem
          - name: kuill_KUBERNETES_CLIENT_KEY
            value: /certs/auth-proxy-key.pem
          - name: kuill_KUBERNETES_CLIENT_CA
            value: /certs/ca.pem
          - name: kuill_VERBOSE
            value: "true"
          - name: kuill_TRACE_REQUESTS
            value: "true"
          ports:
          - containerPort: 8443
            name: https
        
- kind: Service
  apiVersion: v1
  metadata:
    name: kuill
    namespace: kube-system
  spec:
    ports:
    - name: kuill
      port: 8443
      targetPort: 8443
      nodePort: 30443
    selector:
      name: kuill
    type: NodePort
