kind: List
apiVersion: v1
items:

- kind: Namespace
  apiVersion: v1
  metadata:
    name: app-group-1

- kind: ResourceQuota
  apiVersion: v1
  metadata:
    name: compute-resources
    namespace: app-group-1
  spec:
    hard:
      pods: "4"
      requests.cpu: "0.5"
      requests.memory: 400Mi
      limits.cpu: "0.75"
      limits.memory: 500Mi
